# ================== General ==================
Id: Intel.ExtremeTuningUtility
Publisher: Intel
Name: Extreme Tuning Utility
Author: Intel
Description: Intel XTU is a Windows*-based performance-tuning software that enables novice and experienced enthusiasts to overclock, monitor, and stress a system. The software interface exposes a set of robust capabilities common in most enthusiast platforms along with new features available on new Intel® Application Processors and Intel® Motherboards.
AppMoniker: intel-xtu
Tags: hardware, tuning, intel

# ================== License ==================
Homepage: https://downloadcenter.intel.com/download/24075/Intel-Extreme-Tuning-Utility-Intel-XTU
License: Ms-PL
LicenseUrl: https://www.intel.com/content/www/us/en/legal/terms-of-use.html

# ================= Installer =================
MinOSVersion: 10.0.0.0
Version: 7.0.1.4

Switches:
      Custom: /norestart
      Silent: /quiet
      SilentWithProgress: /passive
      Language: en-US

InstallerType: exe
Installers:
  - Arch: x86
    Url: https://downloadmirror.intel.com/29183/eng/XTUSetup.exe
    Sha256: b855a1aadddf46be423c8887a0b3e576a02c4d1737cc2a519317d130e6bc2308
    Scope: machine
